#!/usr/bin/python
import os, sys
import cgi
# missing module fix
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi'))
virtenv = os.environ['APPDIR']+'/virtenv'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
        execfile(virtualenv, dict(__file__=virtualenv))
except:
        pass

from web import wsgiserver
import web
from cgi import parse_qs, escape
import utilities

HOME = 'http://'+os.environ['OPENSHIFT_APP_DNS']+'/'
DIR = os.environ['OPENSHIFT_REPO_DIR']+'wsgi/'

urls = (
    '/', 'index',
    '/display', 'display',
    '/example.html', 'example',
    '/compile', 'compile',
    '/download/(.+)', 'download',
    '/install', 'install'
)

render = web.template.render(DIR+'templates/')

class index:
    def GET(self):
        try:
            f = open(DIR+'static/index.html', 'r')
            web.header('Content-Type', 'text/html')
            return f.read()
        except:
            return DIR+'static/index.html not found' 
class compile:
    def GET(self):
        return 'clsi compiler'
    def POST(self):
        clsi = utilities.clsi()
        to_compile = clsi.parse(web.data())
        [log, pdf] = clsi.run(to_compile)
        if pdf is None:
            log = HOME+"download/"+log
            return render.failure(log)
        else:
            pdf = HOME+'download/'+pdf
            log = HOME+'download/'+log
            return render.success(pdf, log)

class display:
    def GET(self):
        try:
           clsi = utilities.clsi()
           a = web.input(reqid=None, latex=None, density=600)
           to_compile = clsi.webget(a)
           #picture output as out
           log, pdf= clsi.run(to_compile)
           png, pdir = clsi.pdftopng(pdf, a.density)
           f = open(DIR+'static/download/'+png, 'r')
           return f.read()
        except:
            f = open(DIR+'static/display.html', 'r')
            web.header('Content-Type', 'text/html')
            return f.read()
            #return to_compile

class example:
    def GET(self):
        try:
            f = open(DIR+'static/example.html', 'r')
            web.header('Content-Type', 'text/html')
            return f.read()
        except:
            return DIR+'static/example.html not found' 

class download:
    def GET(self, file):
        try:
            f = open(DIR+'static/download/'+file, 'r')
            return f.read()
        except:
            return DIR+'static/download/'+file+' not found'




app = web.application(urls, globals()) # web.py call
application = app.wsgifunc() # Runs the app with wsgi

if __name__ == '__main__':
    app.run()

