#!/usr/bin/python
from web import wsgiserver
import web
import utilities
import os

#DOtcloud
#HOME = os.getenv('DOTCLOUD_PYTHON_HTTP_URL', 'http://clsi-pacbard.dotcloud.com/')
#DIR = '/home/dotcloud/current/'
#Openshift
HOME = os.getenv('OPENSHIFT_APP_DNS')
DIR = os.getenv('OPENSHIFT_REPO_DIR')

urls = (
    '/', 'index',
    '/compile', 'compile',
    '/download/(.+)', 'download',
    '/install', 'install'
)

render = web.template.render(DIR+'templates/')

class index:
    def GET(self):
        try:
            f = open(DIR+'static/index.html', 'r')
            return f.read()
        except:
            return 'File not found' # you can send an 404 error here if you want
        
class compile:
    def GET(self):
        return 'clsi compiler'
    def POST(self):
        clsi = utilities.clsi()
        to_compile = clsi.parse(web.data())
        [log, pdf] = clsi.run(to_compile)
        if pdf is None:
            log = HOME+"download/"+log
            return render.failure(log)
        else:
            pdf = HOME+'download/'+pdf
            log = HOME+'download/'+log
            return render.success(pdf, log)

class download:
    def GET(self, file):
        try:
            f = open(DIR+'static/download'+'/'+file, 'r')
            return f.read()
        except:
            return 'File not found' # you can send an 404 error here if you want
            
application = web.application(urls, globals())

if __name__ == '__main__':
	# this runs when script is started directly from commandline
	try:
		# create a simple WSGI server and run the application
		from wsgiref import simple_server
		print "Running test application - point your browser at http://localhost:8000/ ..."
		httpd = simple_server.WSGIServer(('', 8000), simple_server.WSGIRequestHandler)
		httpd.set_app(application)
		httpd.serve_forever()
	except ImportError:
		# wsgiref not installed, just output html to stdout
		for content in application({}, lambda status, headers: None):
			print content

